import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedComponent1Widget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedSeeallWidget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedCardWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedCardWidget2.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedTHISWEEKWidget1.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedCOMBINEROUTINEWidget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedCardWidget1.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedSUB_TOP_BARWidget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedTOP_BARWidget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl2widget/generated/GeneratedTHISWEEKWidget.dart';

/* Frame Google Pixel 2 XL - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel2XL2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
          LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 1186.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 411.0,
                          height: 1186.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 240, 237, 237),
                                  ),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: 0.0,
                                  bottom: null,
                                  width: null,
                                  height: 240.0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: 0,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            child: GeneratedTOP_BARWidget(),
                                          ))
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 21.0,
                                  top: 187.0,
                                  right: 26.0,
                                  bottom: null,
                                  width: null,
                                  height: 106.0,
                                  child: GeneratedSUB_TOP_BARWidget(),
                                ),
                                Positioned(
                                  left: 20.0,
                                  top: 342.0,
                                  right: null,
                                  bottom: null,
                                  width: 84.0,
                                  height: 21.0,
                                  child: GeneratedTHISWEEKWidget(),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 596.0,
                                  right: 0.0,
                                  bottom: null,
                                  width: null,
                                  height: 154.0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth *
                                        0.9343065693430657;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: constraints.maxWidth *
                                              0.0340632603406326,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            child: GeneratedCardWidget(),
                                          ))
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 759.0,
                                  right: 0.0,
                                  bottom: null,
                                  width: null,
                                  height: 154.0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth *
                                        0.9343065693430657;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: constraints.maxWidth *
                                              0.0364963503649635,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            child: GeneratedCardWidget1(),
                                          ))
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 921.0,
                                  right: 0.0,
                                  bottom: null,
                                  width: null,
                                  height: 154.0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth *
                                        0.9343065693430657;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: constraints.maxWidth *
                                              0.0364963503649635,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            child: GeneratedCardWidget2(),
                                          ))
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 20.0,
                                  top: 570.0,
                                  right: null,
                                  bottom: null,
                                  width: 144.0,
                                  height: 21.0,
                                  child: GeneratedCOMBINEROUTINEWidget(),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 368.0,
                                  right: 0.0,
                                  bottom: null,
                                  width: null,
                                  height: 168.0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth *
                                        0.9051094890510949;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: constraints.maxWidth *
                                              0.04866180048661801,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            child: GeneratedTHISWEEKWidget1(),
                                          ))
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 363.0,
                                  top: 574.0,
                                  right: null,
                                  bottom: null,
                                  width: 38.0,
                                  height: 16.0,
                                  child: GeneratedSeeallWidget(),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: 0.0,
            width: 411.0,
            height: 60.0,
            child: GeneratedComponent1Widget(),
          )
        ]));
  }
}
