import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl3widget/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl3widget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl3widget/generated/GeneratedComponent6Widget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl3widget/generated/GeneratedShareyourexperienceWidget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl3widget/generated/GeneratedComponent2Widget.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl3widget/generated/GeneratedYoufinishedyourroutineHowdoyoufeelThenexttimewillbeeasi.dart';
import 'package:flutterapp/fitapp/generatedgooglepixel2xl3widget/generated/GeneratedComponent4Widget.dart';

/* Frame Google Pixel 2 XL - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel2XL3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1037.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 411.0,
                      height: 823.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.0, 1.0],
                          colors: [
                            Color.fromARGB(255, 103, 156, 236),
                            Color.fromARGB(255, 190, 52, 255)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: -220.0,
                              top: -128.0,
                              right: null,
                              bottom: null,
                              width: 1120.0,
                              height: 1165.0,
                              child: GeneratedComponent6Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 203.0,
                              height: 37.0,
                              child: TransformHelper.translate(
                                  x: 1.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedShareyourexperienceWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: 361.0,
                              right: null,
                              bottom: null,
                              width: 275.0,
                              height: 142.0,
                              child: TransformHelper.translate(
                                  x: 7.00,
                                  y: 0.00,
                                  z: 0,
                                  child:
                                      GeneratedYoufinishedyourroutineHowdoyoufeelThenexttimewillbeeasi()),
                            ),
                            Positioned(
                              left: null,
                              top: 231.0,
                              right: null,
                              bottom: null,
                              width: 275.0,
                              height: 108.0,
                              child: GeneratedComponent4Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 580.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 46.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.3357664233576642;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3333333333333333,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedComponent3Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: null,
                              top: 116.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 93.0,
                              child: GeneratedComponent2Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: 648.0,
                              right: null,
                              bottom: null,
                              width: 331.0,
                              height: 61.0,
                              child: GeneratedGroup5Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
